services:
  - type: web
    name: webar-app
    runtime: node
    env: node
    buildCommand: npm install && npm run optimize
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
